#For wrangle configuration documentation see:
#https://developers.cloudflare.com/workers/tooling/wrangler/configuration/

name = "cfworker-hello-world"
main = "./worker/script.js" # by default, or whatever file webpack outputs
#route = "<only needed if deploying to your domain>"
#zone_id = "<only needed if deploying to your domain>"

# Migration with Webpack to Wrangler: https://developers.cloudflare.com/workers/wrangler/migration/eject-webpack/
[build]
command = "npm run build"
